### ISSUE TITLE
Indigo Disc Pokemon Sprites from PokemonAPI

### ISSUE THREAD

**Issue by Magxus** [CajunAvenger/cajunavenger.github.io#101]
![10277 (1)](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/7b398461-9dfb-45ee-bc49-f002be01854b)
![1024 (1)](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/2ab58a90-132b-4ecd-ab3a-d65fd9207d54)
![1022 (1)](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/d67bee5b-a27a-4895-b179-f4c37fbc61ca)
![1020 (1)](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/1a6e7fa0-6c5f-44f4-be86-00805105b307)
![1019 (1)](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/69561754-d384-4914-b3b0-66f44e06775e)
![10277](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/a96b52b6-5ca2-4d54-917a-902715e11fd5)
![1024](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/6fed5245-0d45-4831-a79f-dd712261d909)
![1022](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/ccaee466-0e55-4b2c-b23e-622aaf950910)
![1020](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/5b8dc048-4662-4a11-b10e-28ae8c2887ee)
![1019](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/5e7ccbc2-d91d-4eb3-a011-199acdb43aad)

Found these Sprites from PokemonAPI

**Comment by CajunAvenger** [comment]
added, we're just short Pecharunt now~
