### ISSUE TITLE
Possible feature ideas

### ISSUE THREAD

**Issue by EdzSpecialSauce** [CajunAvenger/cajunavenger.github.io#106]
In the bottom row where we can select our favorite regional birds, baby Pokémon, pokeball, etc, would it be possible for us to also be able to choose our favorite mega and z-move?

**Comment by CajunAvenger** [comment]
gen 6 gimmick is already favorite mega
how would z move work

**Comment by EdzSpecialSauce** [comment]
z-move could work similarly to favorite pokeball? you would select your
favorite z-move by the z-crystal.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by EdzSpecialSauce** [comment]
As for favorite Mega, I thought it would be nice to have it at the bottom
of the screen along with favorite Gigantamax, but I can understand how that
would be rather repetitive.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
