### ISSUE TITLE
Mawile isn't in the steel type category in the gen 5 section

### ISSUE THREAD

**Issue by MawileEnjoyer** [CajunAvenger/cajunavenger.github.io#108]
She's my favorite pokemon from every gen so I instantly noticed she wasn't in the steel type category in gen 5 even though she was 100% in the game, went and double checked the wiki too but you should go take a look as well.

Figured I'd give this a mention, not sure if there are any others missing but this is the one that immediately stood out to me. 

Have a nice day. :3

**Comment by CajunAvenger** [comment]
Mawile is from gen 3

**Comment by MawileEnjoyer** [comment]
Not sure why what gen they are originally from matters, if it can naturally spawn in a generation before post game, it's part of that generation too.

Doesn't really make any sense to exclude mons that spawn in a generation just because they were in a different game first, some people haven't even played all the games and perhaps their first game was BW which is where they first encountered mawile, why shouldn't it be an option for them?
