### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by Joakingolder** [CajunAvenger/cajunavenger.github.io#11]
Hi.

I was looking for years a tool like you make, and months trying to make it for myself. Whatever.

I have 5 requests for your tool:

1. Can you put Alolan Rattata in the Favorite Regional Mammal?
2. Can you add Aerodactyl-mega in the Favorite Fossil?
3. Can you add a cell for choose your favorite megaevolution?
4. Can you add a cell for choose your favorite Z-move owner? (Pokémon with his own Z-Crystal like Alolan Raichu for example)
5. Can you add alternative forms of the Pokémon at the generations of the original Pokémon too?

Maybe I want many things. At the end, this is your tool, you can refuse my requests or take your owns dessisions, this not gonna change my love for your tool.

Thanks and see ya.

**Comment by CajunAvenger** [comment]
1 & 2, added

3, this would be redundant with gen 6 gimmick forms now

4, doubt it, doesn't have nearly the unity of something like Megas and GMaxes

5, no. you can use Write/Import to overrule the default options.

**Comment by Joakingolder** [comment]
For the point 4 I mean the Pokémon with his own Crystal Z, like Alolan starters, Tapus, Pikachu Cap, Alolan Raichu, Kommo-o, Lycanrocs, Mimikyu, Marshadow, Snorlax, Eevee, Mew and Pikachu
