### ISSUE TITLE
bring back the shiny display!

### ISSUE THREAD

**Issue by leightonisachessplayer** [CajunAvenger/cajunavenger.github.io#112]
ages ago it used to display the shinys of all of them when you clicked the boxes with the shiny charm, so i could look at all their shinys and choose my favouite, but now i went to do it again, and now i cant even click boxes when i have the shiny charm on, i have to rememeber every single pokemons shiny off by heart? no, bring back the old system! please!

**Comment by CajunAvenger** [comment]
When you click the Shiny Charm, a second sentence appears that says "Or click here to make everything shiny." Click that to make everything shiny.
