### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Joakingolder** [CajunAvenger/cajunavenger.github.io#12]
Hi again.

I saw these issues:

1. When you choose "Vanilla Cream", the sprite with Strawberry Sweet fails.
2. Phione not appears in the legendary cell of gen 4, neither favorite mythical.
3. Zarude dada not appears in the favorite mythical.
4. G-Max Urshifu water can be selected in the cell of gen 8 and dark type, but not appears in gen 8 water type.
5. When you import code, the empty spaces in the code not delete the cells selected on the table.

This is for now.

Thanks again and see ya.

**Comment by CajunAvenger** [comment]
Added each of these except Zarude. It falls into the bucket with Genesect and most of the gender sprites where its just not really all that different.

Zarude's image is in the files, so you can Write/Import with ZARUDE_1 though.

**Comment by Joakingolder** [comment]
Ok, the last thing is delete G-Max Urshifu Water from Gen 8 Dark Type cell.
