### ISSUE TITLE
Just two requests

### ISSUE THREAD

**Issue by Verra913** [CajunAvenger/cajunavenger.github.io#16]
Hello! I have a few requests:

1. Can you put Xerneas' active mode?
2. What do you think about adding Ash-Greninja in the Gimmick Forms for Gen VI and Gen VII? I know it's a special case because it's not a mega or anything. I know it was introduced in Gen VII, but it feels weird not including it in Gen VI as well.

That's all, thank you very much!

**Comment by CajunAvenger** [comment]
Currently for both of those, you can put those in with Write/Import. Put in some filler mon, click Write Code, then replace its name with GRENINJA_1 or XERNEAS_1 and Import, it'll put the sprite in there.

Xerneas I can slot in there properly next update.

Not sure on Greninja tho, its more akin to Dusk Lycanroc than regionals or Megas or whichever.
