### ISSUE TITLE
A few inconsistencies

### ISSUE THREAD

**Issue by Rot8erConeX** [CajunAvenger/cajunavenger.github.io#2]
- You have each form of Silvally listed in the appropriate type for Gen 7, but do not do the same for Arceus in Gen 4.
- You have each individual variant for the Floette line and Furfrou shown (as well as all the cores for Minior), but do not do the same for Alcremie or Vivillon.  In Alcremie's case I understand - there's 63 forms and it would bloat the menu!  Might I suggest a two-stage process for these mons?  You pick the default form and then a sub-menu shows up to pick the form you want displayed?  It could also apply for Unown.
- You have a box for favorite Gigantimax form, but not a box for favorite Mega Evolution.  I'd also suggest an option for favorite Tera Jewel, but I don't know if those have sprites yet.
- Less of a thing than the others, but I feel it's worth mentioning: you mention "pikachu clones" rather than "electric rodents", which makes sense since you include Mimikyu among this number (and it is reasonable since it's a literal attempt at a Pikachu clone).  However, this also opens the door for "Pikablu" now known as Marill.  You might want to better clarify the meaning here.
- Likewise, your option for favorite fossil does not include Relicanth, a mon that is both in-universe and IRL old enough to be a fossil.  Maybe change this to "favorite revived fossil" to better clarify.
- (I'd also love to point out the difference between Legendaries and Mythicals, but after actually doing so via Paint.NET I realized why you don't do this: A few gens have like one option each for Mythical.  Maybe just label that header Legend/Mythical.)
- Also, within Gen 8, you have Galarian Linoone displayed right before Obstagoon when I assume it's supposed to be right after Galarian Zigzagoon.  Galarian Meowth and Paldean Wooper do similar things.  I assume this is because whatever you're doing to order them is based on the evolution data?

**Comment by AsparagusEduardo** [comment]
> You have a box for favorite Gigantimax form, but not a box for favorite Mega Evolution. I'd also suggest an option for favorite Tera Jewel, but I don't know if those have sprites yet.

Tera Jewels aren't really Pokémon, so it wouldn't make much sense to add this. It'd be like adding "Favorite Z-Crystal".

> Likewise, your option for favorite fossil does not include Relicanth, a mon that is both in-universe and IRL old enough to be a fossil. Maybe change this to "favorite revived fossil" to better clarify.

I don't feel there's a need to distinguish the fossil group, as it's generally agreed that the term "Fossil Pokémon" refers to Pokémon revived from fossils, which excludes Relicanth.

**Comment by Rot8erConeX** [comment]
> Tera Jewels aren't really Pokémon, so it wouldn't make much sense to add this. It'd be like adding "Favorite Z-Crystal".
Tera Jewels aren't really Pokémon, and neither are Poké Balls, something this tracker already allows you to pick your favorite of.  Some of the hats are cool, some suck.  Let people pick their favorites.

The difference between the Tera Jewel and Z-Crystal is that the crystals all are the same shape, only the color differs.  It'd be interesting to let people pick their favorite Z **Move**, but I feel it'd be hard to do without providing animations for each of them and that is probably beyond the scope of the project.

**Comment by CajunAvenger** [comment]
will be a day or two before i can throw code at this but responding

> You have each form of Silvally listed in the appropriate type for Gen 7, but do not do the same for Arceus in Gen 4.

Silvally is the oversight there

> You have each individual variant for the Floette line and Furfrou shown (as well as all the cores for Minior), but do not do the same for Alcremie or Vivillon.  In Alcremie's case I understand - there's 63 forms and it would bloat the menu!  Might I suggest a two-stage process for these mons?  You pick the default form and then a sub-menu shows up to pick the form you want displayed?  It could also apply for Unown.

Vivillon and Unown are fine to add (maybe get their own box like Eeveelution tho), Alcremie is so disruptive for such a nothing change

> You have a box for favorite Gigantimax form, but not a box for favorite Mega Evolution.  I'd also suggest an option for favorite Tera Jewel, but I don't know if those have sprites yet.

yea Mega wasn't in the original template i'll add this once i have a little more time for moving things around for it. pass on tera and  z crystals

> Less of a thing than the others, but I feel it's worth mentioning: you mention "pikachu clones" rather than "electric rodents", which makes sense since you include Mimikyu among this number (and it is reasonable since it's a literal attempt at a Pikachu clone).  However, this also opens the door for "Pikablu" now known as Marill.  You might want to better clarify the meaning here.

Marill's not anywhere near a pikaclone as Mimikyu

> Also, within Gen 8, you have Galarian Linoone displayed right before Obstagoon when I assume it's supposed to be right after Galarian Zigzagoon.  Galarian Meowth and Paldean Wooper do similar things.  I assume this is because whatever you're doing to order them is based on the evolution data?

yea but i can fix that manually now
