### ISSUE TITLE
Request: Alternative forms sort by importants

### ISSUE THREAD

**Issue by Joakingolder** [CajunAvenger/cajunavenger.github.io#20]
Hi once more.

About the alternative forms that not adding yet, and I sorted by the most to the less importants to add:

1. Type forms of Arceus. Fairy type in gen 6 and the others in gen 4.
2. Pikachu in a cap in gen 7.
3. Spiky-eared Pichu in gen 4.
4. Cosplay Pikachu in gen 6.
5. Sizes of Pumpkaboo and Gourgeist in gen 6.
6. Genesect's ROMs in gen 5.
7. Gender diferences of Pokémon from gens 1, 2, 3 and 4. Hisuian Sneasel too and maybe Eevee too.
8. Starmobile Revavroom in gen 9.
9. Mimikyu Disguise off in gen 7.
10. Sinistea and Polteageist phony and antique in gen 8.

I don't count Xerneas forms because it depends if is in combat or not. The same case for active and inactive forms of Black and White Kyurem.

And these are my arguments:
1. You put the forms of Silvally but not the forms of Arceus.
2. These forms are from event, but you can register them in Pokémon Home
3. Is too from an event and only can stay in HGSS, but I see Eternal Floette and for these reason Spiky-eared Pichu should stay too.
4. The same that the point 3 but with other forms plus.
5. The look is just the size, but the stats are other thing.
6. Maybe the change is too small, but everyone could choose his favorite ROM
7. This is hard to understand. The gender differences appears in gen 4 for Pokémon of gens 1, 2 and 3. Eevee have too gender difference in gen 7 of Let's Go starter, and for wild female starters in gen 8. Maybe you can ignore this.
8. You can't have Starmobile Revavroom, just battle them. But you put Eternatus Eternamax, and I think that you could put these forms too.
9. Maybe anyone choose Mimikyu without active Disguise, but is an alternative form.
10. These are only differents in the microscopic mark of the basement. So this is the reasson why these are in the last point.

Well, this is all.

Thanks for read and see ya.

**Comment by CajunAvenger** [comment]
> You put the forms of Silvally but not the forms of Arceus.

Silvallly forms were removed

> pikachu forms

Yea that seems about as sensible as Furfrou and Ash Greninja and Eternal Floette, sure

> gender sprites, genesect roms, pumpkaboo

The major gender differences are in, I don't want to overload the boxes with a bunch of sprites with differences that are so hard too see like the others do. Maybe i can get something like the Alcremie setup.

> Starmobile

We don't have sprites, if we did then probably addable.

> Sinistea

this is completely invisible

**Comment by Joakingolder** [comment]
Ok. But about the Silvally forms, it can't be selected, but you can add them with the code box of the bottom. That's why I said it. The forms of Silvally still in the code, but the forms of Arceus can't be selected.

For example: you can choose Fire Silvally with "SILVALLY_1", but you can't choose Fire Arceus with "ARCEUS_1"

With the other points, I understand. Thanks for reply me.
