### ISSUE TITLE
New evolutions to old pokemon arent in the gimmicks, like Clodsire, Obstagoon, and Sirfetch'd

### ISSUE THREAD

**Issue by PokeIonYT** [CajunAvenger/cajunavenger.github.io#24]
I looked, and i'm pretty sure they aren't there. It'd be nice to have those.

**Comment by CajunAvenger** [comment]
They're not, cause they're not really forms? Clodsire and Runerigus are close but Purrserker and Sneasler are def distinct from "Galarian Persian" or "Hisuian Weavile", and there's not even an alternate for Obstagoon and Overqwill.

You can use the Write/Import box to put those in your own grid but I don't think they fit the category well enough for the default options.

**Comment by PokeIonYT** [comment]
good point.
