### ISSUE TITLE
I wanted to mention this.

### ISSUE THREAD

**Issue by RdJnEs** [CajunAvenger/cajunavenger.github.io#29]
**I was wondering if you click on the shiny charm, sometimes it changes all the pokemon in the box to the shiny form and sometimes it doesn't work. I was wondering why sometimes it works and sometimes it doesn't.**
**I hope this makes sense.**

**Comment by CajunAvenger** [comment]
When you click on the shiny charm, it adds a second line of text, clicking that text should then turn everything shiny. Are you perhaps sometimes clicking that text accidentally, or clicking far enough away from it that it doesn't register?

**Comment by RdJnEs** [comment]
I didn't notice I pressed that before.
Thanks
