### ISSUE TITLE
Gen 6 Gimmick Forms

### ISSUE THREAD

**Issue by SublimeYadon** [CajunAvenger/cajunavenger.github.io#3]
The only option under Gimmick Forms in Gen 6 is Mega Diancie. The other Megas are only available under their types.
![chrome_mdfMK9aXq5](https://user-images.githubusercontent.com/87366591/222066852-49840848-48d3-4d44-b82f-c05ddc4d9305.png)

**Comment by CajunAvenger** [comment]
Megas and GMaxes are put under their base form's original gen, Regionals and Convergents are put under their introduced gen. If it was not this way, gens 1-5 would have 0 options, gen 6 would have 50, and gen 8 would have 70.
