### ISSUE TITLE
Remove PICHU in fourth gen

### ISSUE THREAD

**Issue by Renato6GS** [CajunAvenger/cajunavenger.github.io#30]
![image](https://user-images.githubusercontent.com/67927947/224459805-37a971cd-129e-4368-b6d4-15ff4fe61705.png)

**Comment by CajunAvenger** [comment]
it's Spiked-Eared Pichu, an alternate form introduced in Gen 4, it belongs here.

**Comment by ThatOneFiddlement** [comment]
That's the Spiked-Eared Pichu, this variant was introduced there
