### ISSUE TITLE
Add Favorite Baby Pokemon category

### ISSUE THREAD

**Issue by ItsKamon** [CajunAvenger/cajunavenger.github.io#32]
1. Add a favorite baby pokemon box
2. Add 3 extra slots for team box( like how in the anime characters will rotate through different sets of mons)
3. Add ukulele pichu
4. Add the pikachus with ash's hats
5. Add spiky Eared pichu, Ukulele Pichu and the pikachus with ash's hats in favorite pika clone box

**Comment by CajunAvenger** [comment]
Baby Pokemon's not bad, we'd have to find a spot for it tho

don't think i'm doing the team thing

Cap Pikachus are already in. No idea what Ukelele Pikachu is?

Adding all the Pikas... maybe. that does start to make that box really big and you can put them in with Write/Import

**Comment by ItsKamon** [comment]
Here's the sprite for ukulele pichu
![Untitled 03-13-2023 10-51-47](https://user-images.githubusercontent.com/126666852/224597895-d2a04921-99f4-4ca1-bd83-72849aa0db16.png)

**Comment by ItsKamon** [comment]
Here's the sprite for ukulele pichu, he appeared in a spin off game in gen 4
![Untitled 03-13-2023 10-51-47](https://user-images.githubusercontent.com/126666852/224598034-4ec9e270-b750-4241-9314-6e72da31f921.png)
