### ISSUE TITLE
Final Favorite Ranked Selection

### ISSUE THREAD

**Issue by nateonline** [CajunAvenger/cajunavenger.github.io#36]
Hey, love the website!

I fee like picking the "final favorite Pokémon" seems a little abrupt. It would be nice to have some way to instead rank all of your favorites from each gen and type in order, so you know your 1st favorite, 2nd, etc.

It would be especially cool if you could just click-and-drag them to rank them.

**Comment by CajunAvenger** [comment]
you might prefer this site's implementation: https://www.dragonflycave.com/favorite.html
