### ISSUE TITLE
Official Artwork Toggle

### ISSUE THREAD

**Issue by MateosOTI** [CajunAvenger/cajunavenger.github.io#37]
I was wondering if there is a limitation that would stop this from being possible, but I think adding a toggle to have the official artwork instead of sprites would make this tool more aesthetically pleasing, and the official artwork also represents many Pokémon personalities in a better way.

This would also fix the visual inconsistencies between the official sprites and the fan-made ones.

**Comment by CajunAvenger** [comment]
1) there are many forms without existing official art, most notably shinies

2) official art is very large, meaning it does not scale down to the template size well

3) official art is very large, meaning having all of it at its normal size will slow down loading dramatically and likely push us over our file size limit. the later could be circumvented by linking from Bulbapedia, but then browsers will not allow you to download the final image

**Comment by MateosOTI** [comment]
I see, good points, I didn't even think about point 1. Sprites it is then.
