### ISSUE TITLE
Shiny Charm doesn't work

### ISSUE THREAD

**Issue by Skarlata5** [CajunAvenger/cajunavenger.github.io#39]
When I click on the shiny charm the pop up window stop happening. I tried in safari, chrome and opera, neither work.

**Comment by CajunAvenger** [comment]
yes. click on the shiny charm again to exit Shiny Mode and you can pick things again.

**Comment by Skarlata5** [comment]
but if I unclick the shiny charm just show me the normal version of the pokes, and I want to see the shinys.

**Comment by CajunAvenger** [comment]
I think you're misunderstanding how the charm works?

When you click on the Shiny Charm, every mon on the grid you click will turn shiny. When you click the Shiny Charm again, those will stay shiny, but you'll go back to picking.

If you want to turn everything, even the mons you see in the pick bubble, shiny, you click the Shiny Charm, then the "Or click here to turn everything shiny" text that shows up. It may take a moment to load the new images, especially if you have a lot of the grid filled.

This is confirmed still working on Chrome and Firefox.

**Comment by MysteriiBousuguru** [comment]
I got an issue with it too. I click on the "Turn Everything Shiny" text and everything even after resetting the grid turns shiny, even with it off.

**Comment by CajunAvenger** [comment]
> I got an issue with it too. I click on the "Turn Everything Shiny" text and everything even after resetting the grid turns shiny, even with it off.

Resetting the grid doesn't change that setting. Just tested it and clicking the Turn Everything Shiny text again returns everything to normal as expected?
