### ISSUE TITLE
Feature request: Ability to "overide" type/generation limits to place any Pokemon in any slot

### ISSUE THREAD

**Issue by jabberwockxeno** [CajunAvenger/cajunavenger.github.io#4]
As an example, i'd personally rather place regional forms in with the generation the original Pokemon debuted in (Say, Galarian Moltres in Gen 1), and would put Hisuian Pokemon in with Generation 9 rather then Generation 8. 

Having the ability to "override" the normal selection options for a given grid and put any Pokemon sprite there instead would be useful in situations like that.

**Comment by CajunAvenger** [comment]
You can do this with the Write/Import box already. Put a filler mon in the box, Write the code, then replace the name with the one you want. For the gimmick forms most of them will be NAME_1 but stuff like Charizard and Urshifu have more numbers so you may want to add them as well to get their code for certain.
