### ISSUE TITLE
gimmick options in the non "favorite gimmick" column

### ISSUE THREAD

**Issue by LeviSkies** [CajunAvenger/cajunavenger.github.io#40]
this isn't really an issue just.. For example in gen 6, I dont like how we have the option to choose mega evolutions for each type. half of the pokemon I chose as my favorite's for gen 6 aren't even from generation (I picked mega rayquaza as my favorite legendary for generation 6 but like yeah technically it was introduced in gen 6 but it isn't really from gen 6 its from gen 3).. If ur going to add that why not add, for instance, mega charizard in the Gen 1 Fire type column? 

I just feel if I want to pick my favorites from each gen they should be original pokemon.. having the favorite gimmick from that gen column is there for a reason is it not?

**Comment by CajunAvenger** [comment]
There's nothing preventing you from just electing not to choose from the Megas? I've seen plenty of people go for that. And it's much easier to ignore the gimmicks for those that want to, rather than to make people who do want to choose the gimmicks have to Write/Import for so many slots.
