### ISSUE TITLE
Forms in their origin region?

### ISSUE THREAD

**Issue by SketchFox7** [CajunAvenger/cajunavenger.github.io#41]
There is an argument to be made that the various forms of each Pokemon be available in the generation of their original forms? Especially Zygarde, as his forms did debut in the Gen 6 anime.

**Comment by CajunAvenger** [comment]
I think it makes more sense to have them in the slot were they were introduced, like the other mons get.

Remember you can use the Write/Import box to put those in for your own grid if you want.
