### ISSUE TITLE
Gigantamax Gengar is missing

### ISSUE THREAD

**Issue by Mawennnnn** [CajunAvenger/cajunavenger.github.io#44]
Gigantamax Gengar isn't selectable in the gen VIII "gimick forms" list. I tried to refresh the window but it didn't help.
![image](https://user-images.githubusercontent.com/128729891/227274158-638eafb1-b4ae-4595-a3d0-0265fa7386a7.png)

**Comment by RexusChrysalis** [comment]
Not only Gigantamax Gengar is missing, all Gigantamax whose base pokemon comes from a generation before gen VIII are not selectable. Strange.

**Comment by CajunAvenger** [comment]
They're in the Gen 1 Gimmick slot
