### ISSUE TITLE
What of these alternate forms could you add?

### ISSUE THREAD

**Issue by Joakingolder** [CajunAvenger/cajunavenger.github.io#45]
Well, after add Pichukelele, I was thinking another forms in Pokémon games that you could add. I find these, and I'll write reasons why can be add and why could be better don't add too.

1. Shadow Lugia from Pokémon XD: Gale of Darkness. This Pokémon are the same that original Lugia, but it was introduced in the third generation. The game that the Pokémon appears can trade with the games of the main series, so it looks a good point. Is a Box Legendary Pokémon too. And his game is played like the main series. Even you can trade and transfer Pokémon from Colosseum and XD finally to Home, like from "Aura" region. However, it can't be trade without be purified and forget the shadow moves.
2. Purple Kecleon from Mystery Dungeon 1: Rescue Team. I'm joking, this Pokémon only is a NPC seller in Rescue Team and Explorers. Is your final decision put this Pokémon or not.
3. Primal Dialga from Mystery Dungeon 2: Explorers. I'm joking again, is exactly like Dialga but with only a different color. You decide if it matters.
4. Bittercold from Mystery Dungeon 3: Gates of Infinity. Forget it, you can fight this… "Pokémon"? I not know, but this have no type, so it must go out because you can't put it without any type.
5. Void Shadows from Mystery Dungeon 4: Super. Forget it again. I played the game and these creatures have types, but their types are random, so you can't put these "Pokémon".
6. Dark Matter from Mystery Dungeon 4: Super. Forget it one more time. Is like Bittercold, it has no type and looks so different to other creatures.
7. Shadow Mewtwo and Shadow Mega Mewtwo X from Pokken Tournament. Ok, these Pokémon forms could be added. Is like Mewtwo and Mega Mewtwo X but shadow. I think you could add it.
8. Costume Pokémon from Pokémon Go. Forget it for last time. Niantic add in Pokémon Go too many Pokémon forms that can't be transferred to home or other games, like armored Mewtwo, clone Pokémon from the first movie, dressed Pokémon, Eevee flower, Pikachu balloons, etc.

Well, this is my issue, thanks you so much for read.

**Comment by CajunAvenger** [comment]
Shadow Lugia, Primal Dialga, and Purple Kecleon are functionally just recolors so those are certainly spriteable.

Shadow Mewtwo a lil more involved but not off the table.

GO Costumes are lacking sprites and often very minor, think I'll skip on those.

rest of the list seems to be a combination of not-typed and not-pokemon, and all not sprited, so those are out as well.

**Comment by Joakingolder** [comment]
And I forget to talk another example like the GO Costumes. I'm talking about the alternate Pokémon from Shuffle and Café ReMix, and in Nintendo Badge Arcade. It was only for mencion, not for add, you know.
