### ISSUE TITLE
Add Favorite Mega and Add Paradox under Gen 9 Gimmicks

### ISSUE THREAD

**Issue by Galaxad** [CajunAvenger/cajunavenger.github.io#46]
I just think this should be here

**Comment by CajunAvenger** [comment]
Favorite Mega is the gen 6 gimmick slot

Paradox to me feels distinct enough from Gen 6 Megas, Gen 7 Regionals, Gen 8 GMax, and Gen 9 Convergents. It also feels less like a "form" given the new Pokedex numbers; and while that does apply to Convergents too, Paradox also has a favorite box in the bottom where Convergents don't (and won't unless they add a bunch more).
