### ISSUE TITLE
Can't download the rendered image on mobile

### ISSUE THREAD

**Issue by ItsKamon** [CajunAvenger/cajunavenger.github.io#5]
When I hold on the picture after pressing the render button, it instead selects the textbox under it. This does not happen when I hold on the image before pressing render

**Comment by CajunAvenger** [comment]
yep, this is the big bug i'm looking at for the moment, once its sorted out i'll be able to just have a Download button instead of the Render-save image set up.

For the time being, you can use the Write/Import box to transfer your choices to a PC where it can be saved properly.

**Comment by CajunAvenger** [comment]
I think this is working now, can others verify?
