### ISSUE TITLE
Spinda problem returns

### ISSUE THREAD

**Issue by LilyArlatto** [CajunAvenger/cajunavenger.github.io#50]
Identical to issue #28, I checked and "SPINDA" was in between my Pokeball and Vivillion choice, yet Spinda's head is still white instead of tan.
![image](https://github.com/CajunAvenger/cajunavenger.github.io/assets/44240334/f35d9613-94b8-4959-9d50-92ca0ea35a9c)
![download](https://github.com/CajunAvenger/cajunavenger.github.io/assets/44240334/a478337e-aecc-46a4-8284-955f0a591458)

UPDATE (literally like 2 mins later): I clicked "import choices" on the thing I literally just exported and then hit download again just to check, and suddenly the bug is gone. Not sure why I had to re-import the choices when the site clearly exported the right thing. Probably worth checking out regardless.
![download(1)](https://github.com/CajunAvenger/cajunavenger.github.io/assets/44240334/15cdf2ec-b503-4bf2-af38-1381f5f49213)

**Comment by CajunAvenger** [comment]
strange, not sure where its going weird this time yet

the import/export thing is cause the export is hard coded to always export that as Spinda, but somehow still managing to get unpicked before you force reload it.
