### ISSUE TITLE
All image links are broken

### ISSUE THREAD

**Issue by soepie7** [CajunAvenger/cajunavenger.github.io#51]
For example, pidgey at https://cajunavenger.github.iofront/PIDGEY.png just gives a DNS error about being unable to load the page. The entire Pokemon Picker is unusable.

**Comment by soepie7** [comment]
For reference, the link https://raw.githubusercontent.com/CajunAvenger/cajunavenger.github.io/main/Front/PIDGEY.png works.

**Comment by shroomibloom** [comment]
yep same for me!

**Comment by leerawktb9** [comment]
I too am experiencing this problem same here for me :( 5/13/23 @ 8:41 (EST)
Greatly appreciate the creators hard work and all their effort into making this in the first place, it's super wonderful.

**Comment by ScrattyBark** [comment]
yea i was hyped to see this thing but all the images don't show up. big friggen sad folks. hopefully this gets fixed soon

**Comment by aR0y2810** [comment]
I have the same issue! It's a great tool, hopefully the bug is fixed soon.

**Comment by CajunAvenger** [comment]
sorry about that all, we're back now 😅
