### ISSUE TITLE
Import moves down 2 rows 

### ISSUE THREAD

**Issue by nl0000** [CajunAvenger/cajunavenger.github.io#6]
I copied the code, and trying to load it back moves all of the selections down two rows, leaving gen 1 and 2 empty.

**Comment by CajunAvenger** [comment]
Is the broken page icon the black and white X? That's for removing your current mon.

Other thing looks like the parser is probably reading blank lines that it shouldn't, i'll fix that up

**Comment by nl0000** [comment]
it looks like a piece of paper with a corner folded and a zig zag rip, ive seen it before but dont know what the technical name is, broken image maybe? i think the blank rows and that error symbol might be connected, it only shows up when i try to load code.

also i just tried a new load, and the top row now gets put into the bottom "team" and favorite "bird, etc" section

**Comment by CajunAvenger** [comment]
may need to reload? everything seems fine on my end ![normal gen 2](https://user-images.githubusercontent.com/12363371/222262079-52cd0549-4b57-4512-9e8c-12344a2573ff.png)

> (edit) but it now fills from the top row. everything moved up, but is in the wrong gen.
ah! put a comma at the top of your code on its own line. then that one will load as the bottom section and the first you have will load into gen 2

**Comment by nl0000** [comment]
okay! the extra comma fixed it, and the broken image is gone. now nothings loading into gen 8 and 9, i even tried 7 lines of just commas and then a row of mons.
(i appreciate your responsiveness!)

**Comment by nl0000** [comment]
sorry nevermind! just did a new write and load and it worked fine! ty again!
