### ISSUE TITLE
Making a similar tool for favourite Pokemon Characters

### ISSUE THREAD

**Issue by sandbuggers** [CajunAvenger/cajunavenger.github.io#66]
Hi, not sure if this is the best place to ask this, but I was thinking of making a similar "favourites grid" picker for the human Pokemon characters, with a per-generation/game layout and categories such as protagonist, rival, gym leader, E4/Champion etc. Would you be happy with letting me adapt your code (with full credit)? It's alright if not, I'll otherwise try build it from scratch. 

Thank you, have a nice day!

**Comment by CajunAvenger** [comment]
sure go for it
