### ISSUE TITLE
Sprites for the Teal Mask new Pokemon and Forms

### ISSUE THREAD

**Issue by PokemonLover1220** [CajunAvenger/cajunavenger.github.io#83]
Sprites Needed
Ogerpon's (Grass)
-Hearthflame Mask (Grass,Fire)
-Wellspring Mask (Grass,Water)
-Conerstone Mask (Grass,Rock)
Exclusive Terastalize forms Including all 4 Exclusive Mask Tera Forms
Bloodmoon Ursaluna (Normal,Ground)
Shiny Sprites needed for all.
Sinistcha (Grass,Ghost)
Shiny Sprites for
Okidogi (Poison, Fighting)
Monkidori (Poison, Psychic)
Fezandipiti (Poison, Fairy)
Poltchageist
Sinistcha
Dipplin
Ogerpon
-Hearthflame Mask 
-Wellspring Mask 
-Conerstone Mask
-Tera Form
Bloodmoon Ursaluna

**Comment by PokemonLover1220** [comment]
Sinistcha and Tera Form for Ogerpon in Gen 9 Gimmick Forms

**Comment by PokemonLover1220** [comment]
Gen 9 Legendary also Needs all of Ogerpon's Mask Forms and All 4 of Ogerpon's Unique Tera Forms

**Comment by CajunAvenger** [comment]
this belongs in #9
