### ISSUE TITLE
Gen 9 DLC mons

### ISSUE THREAD

**Issue by CajunAvenger** [CajunAvenger/cajunavenger.github.io#9]
Putting this here to head off any others, yes stuff will get added, it may take some time tho. I do want a combination of sprites and the Pokemon "existing" before it gets added (and kinda hard to add stuff before we know its types). I have a little experience with spriting so I may tackle these eventually but welcome anyone better who wants to pitch in.

Completed
- Walking Wake (Jordanos)
- Iron Leaves (Jordanos)
- Dipplin (RetroNC)
- Okidogi (RetroNC)
- Poltchageist (PokeAPI)
- Sinistcha (PokeAPI)
- Munkidori (PokeAPI)
- Fezandipiti (PokeAPI)
- Ogerpon [All Forms] (PokeAPI)
- Ursaluna Blood Moon (PokeAPI)
- Archaludon (RetroNC)
- Raging Bolt (PokeAPI)
- Iron Crown (PokeAPI)
- Terapagos [Terastal] (PokeAPI)
- Hydrapple (PokeAPI)
- Gouging Fire (PokeAPI)
- Iron Boulder (PokeAPI)
- Terapagos [Normal] (PokeAPI)
- Terapagos [Stellar] (PokeAPI)

Missing sprite
- Pecharunt

**Comment by CajunAvenger** [comment]
Walking Wake and Iron Leaves are now live. That'll probably be all we can add until the DLC properly releases in a few months, but I will tinker with spriting the other five in the meantime since we have the official artwork to work with.

**Comment by RealRetroNC** [comment]
Hey there, I can provide the sprites for Iron Crown, Raging Bolt, Dipplin, Archaludon and the rest (except the baby Terapagos) if you're interested! (attachment is an example of my sprites)
![raging bolt thumbnail](https://github.com/CajunAvenger/cajunavenger.github.io/assets/142313692/8f1dc467-de3f-4d24-b19c-9fbbcea4a569)

**Comment by CajunAvenger** [comment]
> Hey there, I can provide the sprites for Iron Crown, Raging Bolt, Dipplin, Archaludon and the rest (except the baby Terapagos) if you're interested! (attachment is an example of my sprites)
> 
> ![raging bolt 96x96](https://user-images.githubusercontent.com/142313692/260699265-82911515-35c4-4494-add8-2bc5229262f7.png)

would love to have them!

**Comment by RealRetroNC** [comment]
Awesome! I have a DeviantArt page for all of my sprites where you can download them, or if you want to I can send them to you
privately some place else! (https://www.deviantart.com/retronc - in the "Gen 9 Pokemon" gallery!)
