### ISSUE TITLE
New Suggestions

### ISSUE THREAD

**Issue by ImDaCook** [CajunAvenger/cajunavenger.github.io#92]
Ok so I have a few suggestions for the picker:
1: Put in a feature for regional mono type dogs (cause they exist).
2: Add in Sinistcha, Bloodmoon Ursaluna and Ogerpon’s masks.
3: Also put in a feature for Pokémon that are “counterparts” to each other physically.
4: Put in a feature for Pokémon gender wise.
5: Add in cries (i.e.) when selecting a Pokémon
6: Add in an option to select artstyles, be it Ken Sugimori art, HOME 3D renders, the small SV-style icon renders, the Dream Artwork or just their colour palette.

**Comment by CajunAvenger** [comment]
> Put in a feature for regional mono type dogs (cause they exist).

? not really. gen 4 doesn't have one, gen 9 has 2, and there's no throughline between then other than "is a dog", the Rattata-likes are a very consistent archetype

> Add in Sinistcha, Bloodmoon Ursaluna and Ogerpon’s masks.

they'll be in when we've got sprites

> Put in a feature for Pokémon gender wise.

Significant gender differences are already given. Minor gender differences [can be added with the import box](https://github.com/CajunAvenger/cajunavenger.github.io/blob/main/form_doc.txt)

> Add in an option to select artstyles

those artstyles have many things missing we don't have the storage space for them regardless

> Also put in a feature for Pokémon that are “counterparts” to each other physically.
> Add in cries (i.e.) when selecting a Pokémon

pass
