### ISSUE TITLE
Indigo Disk Mons

### ISSUE THREAD

**Issue by seaguhl** [CajunAvenger/cajunavenger.github.io#99]
Adding the new DLC mons from Indigo Disk

**Comment by CajunAvenger** [comment]
if you're not providing sprites this is already #9

**Comment by Magxus** [comment]
![20240105_094137](https://github.com/CajunAvenger/cajunavenger.github.io/assets/155765410/aa3493b4-cd54-4368-8f66-8a8b89200917)
Made by @ezeart_ on twitter
